# Spring Boot Configuration
spring.application.name=student-management

# Active Profile (defaults to dev/H2 database)
spring.profiles.active=dev

# Server Port
server.port=8081

# OpenAPI Swagger UI Configurations
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

# Format JSON responses nicely
spring.jackson.serialization.indent_output=true
